<?php

namespace App\Http\Middleware;

use App\Providers\RouteServiceProvider;
use Closure;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Symfony\Component\HttpFoundation\Response;

class AdminRedirectIfAuthenticated
{
    /**
     * Handle an incoming request.
     *
     * This method is responsible for handling an incoming request. If the 'admin' guard is checked and the user is
     * authenticated, it will redirect the user to the 'admin.dashboard' route. Otherwise, it will pass the request to
     * the next middleware or route handler using the $next callback.
     *
     * @param  \Illuminate\Http\Request  $request The incoming request.
     * @param  \Closure  $next The next middleware or route handler.
     * @param  string  ...$guards The guards to check for authentication.
     *
     * @return \Illuminate\Http\Response The response generated by the middleware or route handler.
    */
    public function handle(Request $request, Closure $next, string ...$guards): Response
    {
        if (Auth::guard('admin')->check()) {
            return redirect()->route('admin.dashboard');
        }
        return $next($request);
    }
}